---
title: "2021-12-14-Spice_Girls"
author: "Kristen A, kkakey"
date: "12/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
```

```{r}
studio_album_tracks <- readr::read_csv("https://github.com/jacquietran/spice_girls_data/raw/main/data/studio_album_tracks.csv")
lyrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-12-14/lyrics.csv')
```

```{r}
lyrics <- lyrics %>%
  group_by(song_name) %>%
  # add line number to each song
  mutate(line_number = row_number()) %>%
  ungroup() %>%
  # Fix song name
  mutate(song_name = ifelse(str_detect(song_name, "Say You"), "Say You'll Be There", song_name))
```

```{r}
# top 7 songs
n <- 7
```

```{r}
top_danceability_scores <- studio_album_tracks %>%
  arrange(desc(danceability)) %>%
  head(n) %>%
  select(danceability)

top_danceability_albums <- studio_album_tracks %>%
  arrange(desc(danceability)) %>%
  head(n) %>%
  select(album_name)

most_danceable_songs <- studio_album_tracks %>%
  arrange(desc(danceability)) %>%
  head(n) %>%
  pull(track_name)

# get most sung chorus lyrics for each song
full_df <- as.data.frame(matrix(ncol = 2, nrow = 0))
for (songname in most_danceable_songs) {
  
  first_line <- lyrics %>%
    filter(song_name==songname) %>%
    select(line_number, line) %>%
    count(line) %>%
    arrange(desc(n)) %>%
    head(1) %>%
    pull(line)
  
  first_line_num <- lyrics %>%
    filter(song_name==songname,
           line==first_line) %>%
    head(1) %>%
    pull(line_number)
  
  if (songname=="Love Thing") {
    top_lines <- first_line
  } else {
  top_lines <- lyrics %>%
    filter(song_name==songname,
           line_number>=first_line_num & section_name=="Chorus", line_number<(first_line_num+4)) %>%
    pull(line) 
  }
  
  df<- data.frame(cbind(top_lines, rep(songname,length(top_lines))))
  colnames(df)  <- c("lines", "songname")
  full_df <- rbind(full_df, df)
}
```

```{r}
background_colors <- c("#E9495C", "#F9D749", "#F096C3", "#D2DA47", "#F3D0CF",
                       "#E9495C", "#F9D749", "#F096C3", "#D2DA47", "#F3D0CF")

plot_func <- function(i) {
  
  myplots[[i]] <- ggplot() +
    geom_text(aes(x=.9,y=2,label=top_danceability_scores[i,],family="ClubbedToLife"), size=12) +
    geom_text(aes(x=1.25,y=2,label=most_danceable_songs[i],family="MustangSans"), size=16) +
    geom_text(aes(x=1.25,y=.7,label=paste(top_danceability_albums$album_name[i], "album", sep=' '),
                family="Poppins-Italic"), size=3) +
    geom_text(aes(x=1.75,y=2,label=paste0('"',paste(full_df[full_df$songname==most_danceable_songs[i],]$lines, 
                                                   collapse = '\n'),'"'),
                  family="Anothershabby_pro_regular_v3_trial", fontface="bold"), size=6) +
    xlim(.85,2) + ylim(0,4) +
    theme_void() +
    theme(plot.background = element_rect(color=background_colors[i], fill=background_colors[i])) 
}

myplots <- list()
finalplots <- lapply(seq(1,7), plot_func)

cowplot::plot_grid(plotlist=finalplots, greedy=F, ncol=1) +
  ggsave(paste0("all_plots-", n,".png"), width=13, height=10)
```

```{r}
# title plot
ggplot() +
  geom_text(aes(x=1.22,y=3.5,label="The most",family="MustangSans"), size=16, color="white") +
  geom_text(aes(x=1.57,y=3.5,label="danceable",family="ClubbedToLife"), size=16, color="white") +
  ggtext::geom_richtext(aes(x=1.4,y=1.5,label=paste0("<span style = 'color:#E9495C'>", "S","</span>",
                                                      "<span style = 'color:#F9D749'>", "p","</span>",
                                                      "<span style = 'color:#F096C3'>", "i","</span>",
                                                      "<span style = 'color:#D2DA47'>", "c","</span>",
                                                      "<span style = 'color:#F3D0CF'>", "e","</span>",
                                                      "<span style = 'color:#E9495C'> ", "Girls","</span>",
                                                      "<span style = 'color:white'> ", "Songs","</span>"
                                                ), family="MustangSans"), 
                        size=16, fill = NA, label.color = NA) +
  geom_text(aes(x=1.94,y=.3,label="danceability scored between 0 and 1",family="MustangSans"), size=3, color="black") +
  xlim(.85,2) + ylim(0,5) +
  theme_void() +
  theme(plot.background = element_rect(color="#445552", fill="#445552")) +
  ggsave("plot-title.png", height=2, width=10)
```

```{r}
ggdraw() + 
  draw_image("plot-title.png", scale = 1, x = 0,y = .31) +
  draw_image(paste0("all_plots-", n,".png"), scale = 1, x = 0,y = -.12) +
  theme(plot.background = element_rect(color="#445552", fill="#445552")) +
  ggsave(paste0("final-",n,".png"), width=10, height=11)
```


[Mustang Sans](https://drive.google.com/file/d/1xCaPDz761aWLZqbZD_lDM25XQiUm6r9_/view)
[Quirlycues Regular](https://www.1001fonts.com/quirlycues-font.html)


