---
title: "2020-04-28_Broadway"
author: "Kristen A"
date: "5/31/2020"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(here)
library(magick)
library(grid)


grosses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv', guess_max = 40000)
synopses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/synopses.csv')
cpi <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/cpi.csv')
pre_1985_starts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/pre-1985-starts.csv')
```


```{r}
grosses %>%
  filter(year(grosses$week_ending) >= 2010) %>%
  group_by(show, week_number) %>%
  mutate(tot_performance = sum(performances)) %>%
  # Average number of seats sold for each performance/preview of that weeek
  mutate(avg_pct_filled_wk = case_when(
    performances > 0 & previews ==0 ~ (seats_sold / seats_in_theatre)/performances,
    previews > 0 & performances ==0 ~ (seats_sold / seats_in_theatre)/previews,
    previews > 0 & performances > 0 ~ (seats_sold / seats_in_theatre)/(previews + performances)
  )) %>%
  ungroup() %>%
  group_by(show) %>%
  #what was the highest average capacity a show reached
  mutate(highest_cap = max(avg_pct_filled_wk)) %>% 
  arrange(show, week_number) %>%
  # distinct(show, week_number, .keep_all = T) %>%
  #filter to shows that reached a max. pct capacity of 95%+
  filter(highest_cap > .95) -> df_sub

#Look at shows that include week 1 stats
df_sub %>%
  group_by(show) %>%
  filter(week_number==1) %>%
  distinct(show) %>% pull(show) -> show_titles


df <- df_sub[df_sub$show %in% show_titles,] 


df %>%
  arrange(week_ending) %>%
  group_by(show) %>%
  mutate(wk_by_start =  row_number(show),
         start_year = year(week_ending)) -> df

df %>%
  group_by(show) %>%
  filter(wk_by_start < 51) %>%
  arrange(desc(highest_cap)) -> high_cap

high_shows = list()
for (s in unique(high_cap$show)) {
  high_cap %>%
  filter(show==s,
        avg_pct_filled_wk==highest_cap) -> yes
  high_shows[[s]] <- yes
}
library(plyr)
high_shows <- ldply(high_shows, data.frame)


high_shows %>%
  group_by(.id) %>%
  arrange(desc(highest_cap)) %>%
  distinct(show, .keep_all = T) %>% pull(show) -> final_shows
final_shows <- final_shows[1:5]

df_final <- df[df$show %in% final_shows,] 

df_final %>%
  arrange(week_ending) %>%
  group_by(show) %>%
  mutate(start_year = year(week_ending)) -> df_final

df_final %>%
  arrange(week_ending) %>%
  mutate(start_year = year(week_ending)) -> df_final
```


```{r}
# Load images
curtain <- png::readPNG("images/curtain-blur.png")

star <- png::readPNG(here("images/star3.png"))
star <- rasterGrob(star, interpolate=TRUE, height = .24, width = .45)

circle <- png::readPNG(here("images/circle.png"))
circle <- rasterGrob(circle, interpolate=TRUE, height = .23, width = .35)
```


Red curtain plot
```{r}
ggplot(df_final, aes(wk_by_start, avg_pct_filled_wk, group=show)) + 
  background_image(curtain) +
  geom_point(aes(colour=show)) + geom_line(aes(colour=show)) + 
  ggtitle("Record Audiences:") + 
  ylab("Average Audience Capacity Each Week") +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1.09)) +
  scale_x_continuous(name="Week of Production", limits=c(-4, 55)) +
   theme(text=element_text(family="Broadway"),
        legend.position = "none",
        plot.background = element_rect(fill = 'black'),
        axis.text.x = element_text(size= 12, color="#B89000"),
        axis.text.y = element_text(size= 12, color="#B89000"),
        plot.title = element_text(size= 13.5, color="#B89000"),
        axis.title = element_text(size= 12, color="#B89000"),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = -15, l = 0)),
        plot.subtitle = element_text(size= 12, color="#B89000", family="LibreBodoni-Bold", face="bold"),
        plot.caption = element_text(size= 9, color="#B89000", family="LibreBodoni-Bold", face="bold"),
        panel.border = element_rect(colour = "black", fill=NA, size=.05)
        ) +
  annotate("text",label="★", x=44, y=1.034754, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF", x=43.95, y=1.034, size=2, family = "HiraKakuPro-W3",color="black") +
  annotate("text",label="★", x=11, y=1.036644, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="★", x=27, y=1.03574, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF",  x=26.95, y=1.035, size=2, family = "HiraKakuPro-W3", color="black") +
  annotate("text",label="★", x=5, y=1.03634, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF",  x=12, y=1.0282205, size=2, family = "HiraKakuPro-W3", color="black") +
  annotate("text",label="★", x=11, y=1.037351, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +

  annotation_custom(grob = star, 
                    ymin = .64,ymax= .715,xmin = 40.5+3,xmax = 42.5+4.6) +
    annotation_custom(grob = circle, 
                    ymin = .658,ymax= .728,xmin = 47.2+1,xmax = 49.2+3.2) +
  coord_cartesian(clip = "off") +
  annotate("label", x = 50, y = 1.06, size=3, label ='Oklahoma!, 2011', family="LibreBodoni-Bold", face="bold",
           color="#faa32a") +
  annotate("label", x = 9.5, y = 1.07, size=3, label ='Harvey, 2017',family="LibreBodoni-Bold",color="#0022B8") +
  annotate("label", x = 18.5, y = 1.055, size=3, label ='Lady Day, 2010', family="LibreBodoni-Bold",color="#3e8e9f") +
  annotate("label", x = -1.3, y = 1.06, size=3, label ='Motwown, 2012', family="LibreBodoni-Bold", color="#4aa608") +
  annotate("label", x = 32.5, y = 1.04, size=3, label ='Annie, 2012', family="LibreBodoni-Bold", face="bold", color="#d086fe") +
  scale_colour_manual(values=c("#3e8e9f", "#0022B8" ,"#d086fe", "#4aa608", "#faa32a")) + 
  labs(
    subtitle = "Broadway Musicals that reached highest audicence capacities in their first\n 50 weeks of opening (and sometimes also closing)",
    caption=c("closing show\nhighest avg. audience")) 

# ggsave(filename = "broadway_tidytues.png", dpi = 300, width = 8, height = 5)
```


Gray background plot
```{r}
star <- png::readPNG(here("images/star3.png"))
star <- rasterGrob(star, interpolate=TRUE, height = .08, width = .45)

circle <- png::readPNG(here("images/bcircle.png"))
circle <- rasterGrob(circle, interpolate=TRUE, height = .13, width = .5)


ggplot(df_final, aes(wk_by_start, avg_pct_filled_wk, group=show)) + 
  geom_point(aes(colour=show)) + geom_line(aes(colour=show)) + 
  ggtitle("Record Audiences:") + 
  ylab("Average Audience Capacity Each Week") +
  scale_y_continuous(labels = scales::percent, limits = c(.79, 1.09)) +
  scale_x_continuous(name="Week of Production", limits=c(-4, 55)) +
   theme(text=element_text(family="Broadway"),
        legend.position = "none",
        plot.background = element_rect(fill = '#4f4d4d'),
        axis.text.x = element_text(size= 12, color="#CEAE1F"),
        axis.text.y = element_text(size= 12, color="#CEAE1F"),
        plot.title = element_text(size= 13.5, color="#CEAE1F"),
        axis.title = element_text(size= 12, color="#CEAE1F"),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = -15, l = 0)),
        plot.subtitle = element_text(size= 12, color="#CEAE1F", family="LibreBodoni-Bold", face="bold"),
        plot.caption = element_text(size= 9, color="#CEAE1F", family="LibreBodoni-Bold", face="bold"),
        panel.border = element_rect(colour = "#4f4d4d", fill=NA, size=.05),
        panel.background = element_rect(colour = "#4f4d4d", fill=NA),
        panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()
        ) +
  annotate("text",label="★", x=44, y=1.034754, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF", x=43.95, y=1.034, size=2, family = "HiraKakuPro-W3",color="black") +
  annotate("text",label="★", x=11, y=1.036644, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="★", x=27, y=1.03574, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF",  x=26.95, y=1.035, size=2, family = "HiraKakuPro-W3", color="black") +
  annotate("text",label="★", x=5, y=1.03634, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotate("text",label="\u25CF",  x=12, y=1.0282205, size=2, family = "HiraKakuPro-W3", color="black") +
  annotate("text",label="★", x=11, y=1.037351, size=4.5, family = "HiraKakuPro-W3", color="#F6D447") +
  annotation_custom(grob = star, 
                    ymin = .64,ymax= .70+.12,xmin = 40.5+3,xmax = 42.5+4.6) +
    annotation_custom(grob = circle, 
                    ymin = .658,ymax= .718+.105,xmin = 47.2+1,xmax = 49.2+3.2) +
  coord_cartesian(clip = "off") +
  annotate("label", x = 50, y = 1.05, size=3, label ='Oklahoma!, 2019', family="LibreBodoni-Bold", face="bold",
           color="#faa32a") +
  annotate("label", x = 9.5, y = 1.07, size=3, label ='Harvey, 2012',family="LibreBodoni-Bold",color="#0022B8") +
  annotate("label", x = 18.5, y = 1.055, size=3, label ='Lady Day, 2014', family="LibreBodoni-Bold",color="#3e8e9f") +
  annotate("label", x = -1.5, y = 1.05, size=3, label ='Motown, 2013', family="LibreBodoni-Bold", color="#4aa608") +
  annotate("label", x = 32.3, y = 1.04, size=3, label ='Fun Home, 2015', family="LibreBodoni-Bold", face="bold", color="#d086fe") +
  scale_colour_manual(values=c("#3e8e9f", "#0022B8" ,"#d086fe", "#4aa608", "#faa32a")) + 
  labs(
    subtitle = "Broadway Musicals that reached highest audicence capacities in their first\n 50 weeks of opening (and sometimes also closing)",
    caption=c("closing show\nhighest avg. audience")) 

# ggsave(filename = "broadway_tidytues2.png", dpi = 300, width = 8, height = 5)
```




