---
title: "2021-05-11-Internet_Access"
author: "Kristen A, kkakey"
date: "5/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(cowplot)
library(ggtext)
```

```{r}
broadband <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-11/broadband.csv')

broadband$`BROADBAND AVAILABILITY PER FCC` <- as.double(broadband$`BROADBAND AVAILABILITY PER FCC`)
broadband$`BROADBAND USAGE` <- as.double(broadband$`BROADBAND USAGE`)

broadband <- broadband %>%
  rename(broadband_availability_per_fcc=`BROADBAND AVAILABILITY PER FCC`,
         broadband_usage = `BROADBAND USAGE`) %>%
  mutate(GEOID = stringr::str_pad(as.character(`COUNTY ID`), 5, pad = "0"))

states <- read_sf('./output-data/states.shp', crs=2163) 
counties <- read_sf('./output-data/counties.shp', crs=2163) 

counties <- counties %>%
  left_join(., broadband, on="GEOID")
```

```{r}
## maps ##

# create bins 
counties$broadband_availability_per_fcc_cat <- cut(counties$broadband_availability_per_fcc, 
    breaks = seq(0,1,.2), 
    labels = c("20%","40%", "60%","80%", "100%"))

counties$broadband_availability_per_fcc_cat2 <- with(counties, cut(broadband_availability_per_fcc,
   breaks = qu <- quantile(broadband_availability_per_fcc, probs = seq(0,1, by=0.2), na.rm=T),
   labels = qu[-1], include.lowest=TRUE))

counties$broadband_usage_cat <- cut(counties$broadband_usage, 
    breaks = seq(0,1,.2), 
    labels = c("20%","40%", "60%","80%", "100%"))

counties$broadband_usage_cat2 <- with(counties, cut(broadband_usage,
   breaks = qu <- quantile(broadband_usage, probs = seq(0,1, by=0.2), na.rm=T),
   labels = qu[-1], include.lowest=TRUE))

# plots
ggplot() +
  geom_sf(data=counties, aes(fill=broadband_availability_per_fcc_cat), size=.2) +
  geom_sf(data=states, size=.2, color="black", fill=NA) +
  scale_fill_brewer(palette = "YlOrBr", na.value = "grey80",
                  name="") +
  theme_void() +
  theme(text = element_text(family = "AveriaSerifLibre-Regular", color="white"),
        plot.title = element_text(hjust=.2, vjust=-1),
        plot.background = element_rect(fill="transparent", color="transparent"),
        panel.background = element_rect(fill="transparent", color="transparent"),
        legend.position = c(.95,.2)) +
  guides(fill = guide_legend(override.aes = list(size = 1, color=NA))) +
  ggtitle("Broadband Availability") +
  ggsave("plot-1.png",height=5, bg = "transparent")

ggplot() +
  geom_sf(data=counties, aes(fill=broadband_usage_cat), size=.2) +
  geom_sf(data=states, size=.2, color="black", fill=NA) +
  scale_fill_brewer(palette = "YlOrBr", na.value = "grey80",
                  name="") +
  theme_void() +
  theme(text = element_text(family = "AveriaSerifLibre-Regular", color="white"),
        plot.title = element_text(hjust=.2, vjust=-1),
        plot.background = element_rect(fill="transparent", color="transparent"),
        panel.background = element_rect(fill="transparent", color="transparent"),
        legend.position = "none") +
  ggtitle("Broadband Usage") +
  ggsave("plot-2.png",height=5, bg = "transparent")

# combine two map plots
ggdraw() + 
  draw_image("plot-1.png", scale = 1, x = 0,y = .25) +
  draw_image("plot-2.png", scale = 1, x = 0,y = -.25) +
  ggsave("combined_plot-test.png", height = 10, bg = "transparent")
```


```{r}
## averages by state ##
df <- counties %>%
  as.data.frame() %>%
  group_by(STATEFP) %>%
  mutate(avg_avail = round(mean(broadband_availability_per_fcc, na.rm=T),3),
         avg_use = round(mean(broadband_usage, na.rm = T),3)) %>%
  select(STATEFP, avg_avail, avg_use) %>% distinct() %>%
  arrange(desc(avg_avail), desc(avg_use)) 

df$state_name <- cdlTools::fips(df$STATEFP,to='Name')
df$state_name = with(df, reorder(state_name, avg_avail))

# plot
ggplot(df) +
  geom_segment(aes(x=state_name, xend=state_name, 
                   y=avg_use,yend=avg_avail), color="grey80") +
  geom_point(aes(x=state_name, y=avg_avail), color="#7FC29B", size=2.2) +
  geom_point(aes(x=state_name, y=avg_use), color="#F5AC72", size=2.2) +
  coord_flip() +
  theme(plot.title = element_markdown(margin = margin(t = 7, b = 14, l = 0)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(family = "AveriaSerifLibre-Regular", color="white"),
        axis.text = element_text(color="white"),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_line(color="white"),
        plot.background = element_rect(fill="transparent", color="transparent"),
        panel.background = element_rect(fill="transparent", color="transparent")) +
  xlab("") + ylab("Average Value") +
  ggtitle(paste0("<span style = 'color:white'>Average Internet </span>",
"<span style = 'color:#7FC29B'>Availability </span>",
"<span style = 'color:white'>and </span>",
"<span style = 'color:#F5AC72'>Usage </span>",
"<span style = 'color:white'>by State </span>")) +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
  ggsave("plot3.png", height = 10, bg = "transparent")
```


```{r}
# combine all plots
ggdraw() + 
  draw_image("combined_plot.png", scale = 1, x = -.24,y = 0) +
  draw_image("plot3-test.png", scale = 1, x = .24,y = 0) +
  draw_label("Broadband Internet Access Accross the Continental U.S",size=16,y=1.02,fontfamily="AveriaSerifLibre-Regular", color = "white") +
  theme(plot.background = element_rect(fill="#255F85", color = "#255F85"),
        panel.background = element_rect(fill="#255F85", color = "#255F85"),
        plot.margin = unit(c(t=1, r=0, b=.4, l=0), "cm")) +
  ggsave("combined_plot-final.png", height = 9.5, width=13.6) 
```


***********************************************************************************************
***********************************************************************************************
***********************************************************************************************

Counties with the most and least internet usage and 2019 income

```{r}
states_most <- counties %>%
  as.data.frame() %>%
  arrange(desc(broadband_usage)) %>%
  head(5) %>%
  select(`COUNTY NAME`, ST, STATEFP,COUNTYFP,broadband_usage) %>%
  pull(STATEFP)


states_least <- counties %>%
  as.data.frame() %>%
  arrange(broadband_usage) %>%
  head(5) %>%
  select(`COUNTY NAME`, ST, STATEFP,COUNTYFP,broadband_usage) %>%
  pull(STATEFP)

stateget <- unique(c(unique(states_most), unique(states_least)))

counties_most <- counties %>%
  as.data.frame() %>%
  arrange(desc(broadband_usage)) %>%
  head(5) %>%
  select(`COUNTY NAME`, ST, STATEFP,COUNTYFP,broadband_usage) %>%
  pull(COUNTYFP)

counties_least <- counties %>%
  as.data.frame() %>%
  arrange(broadband_usage) %>%
  head(5) %>%
  select(`COUNTY NAME`, ST, STATEFP,COUNTYFP,broadband_usage) %>%
  pull(COUNTYFP)

c_most <- data.frame(states_most,counties_most) %>%
  mutate(state_co = paste0(states_most,counties_most))
c_least <- data.frame(states_least,counties_least) %>%
  mutate(state_co = paste0(states_least,counties_least))
```

```{r}
library(censusapi)

# Census API key
source("/Users/kristenakey/Desktop/R/api_key/census_api_key.R")

apis <- listCensusApis()
### MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)
variables <- c("B19013_001E")

income_df <- data.frame()
for (s in stateget) {
  counties_census <- getCensus(name = "acs/acs5",
      vintage = 2019,
      vars = variables,
      region = "county:*",
      regionin = paste("state:", s, sep=""),
      key=key)
  income_df <- rbind(income_df, counties_census)
}

income_df <- income_df %>%
  mutate(state_co = paste0(state,county),
         high = ifelse(state_co %in% c_most$state_co,1,0)) %>%
  filter(state_co %in% c(c_most$state_co, c_least$state_co)) %>%
  arrange(B19013_001E) %>%
  left_join(., counties %>%
        as.data.frame() %>%
        select(STATEFP, COUNTYFP, ST, `COUNTY NAME`, broadband_usage) %>%
        rename(state = STATEFP, county = COUNTYFP), by=c("state", "county"))

income_df <- income_df %>%
  mutate(name = paste0(`COUNTY NAME`, ", ", ST),
         usage = paste0(broadband_usage * 100,"%"),
         high_low = ifelse(usage=="1%",0,1)) %>%
  select(name, usage, B19013_001E, high_low)
```

