---
title: "2020-12-01_Toronto_Shelters"
author: "Kristen A, kkakey"
date: "12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(viridis)
library(scales)
```

```{r}
shelters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-01/shelters.csv')
```

```{r}
shelters <- shelters %>%
  group_by(facility_name, occupancy_date) %>%
  mutate(prop_full = occupancy / capacity,
         prop_full = round(prop_full*100,2)) %>%
  ungroup()  %>%
  arrange(occupancy_date)

# add date variables
shelters$month <- month(as.POSIXlt(shelters$occupancy_date, format="%Y/%m/%d"))
shelters$year <- year(as.POSIXlt(shelters$occupancy_date, format="%Y/%m/%d"))
shelters <- shelters %>%
  mutate(month_year = paste0(month,"-",year))
shelters$weekday <- wday(
  shelters$occupancy_date,
  label = T,
  abbr = TRUE,
  week_start = getOption("lubridate.week.start", 1)
)
shelters$weeknum <- week(shelters$occupancy_date)
shelters$daynum <-day(shelters$occupancy_date)
```


```{r}
data <- shelters %>%
  filter(!is.na(prop_full), prop_full!=Inf) %>%
  group_by(occupancy_date) %>%
  mutate(avg_prop_full = mean(prop_full)) %>%
  select(avg_prop_full , month_year, year, weekday, daynum, weeknum) %>%
  distinct()


ggplot(data, aes(x = weeknum, y = weekday, fill = avg_prop_full)) +
  geom_tile(col = "black", width = .9, height = .9) +
  facet_wrap(vars(year), strip.position = "top", nrow = 3) +
  scale_fill_viridis(option="inferno", end = .9, labels = function(x) paste0(x, "%"), name="", direction = -1) +
  scale_x_continuous(expand = c(0, 0),
                    breaks = seq(1, 52, length = 12),
                    labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))  +
  xlab("") + ylab("") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        text = element_text(family="Lato"),
        legend.justification = c(.95, 0),
        legend.position = "bottom",
        legend.margin = margin(-0.25,-0.5,0,-0.5, unit="cm"),
        plot.margin =  margin(1.5,1.5,1,1, unit="cm"),
        legend.key.width = unit(.8, "cm"),
        plot.title = element_text(vjust=2.4, size=14),
        plot.subtitle = element_text(size=9, vjust=1),
        plot.caption = element_text(size=7, vjust=-15)
        ) +
  ggtitle("Average Homeless Shelter Capacity, Toronto") +
  labs(subtitle = paste("For the years of available data, the average capacity of Toronto homeless shelters", 
                        "has been over 90%.",
                        "\nAnd most recently, in 2019, 3/4 of the year had an average homeless shelter",
                        "capacity at or above\n95% in Toronto.", sep=" "),
       caption = "Data: {opendatatoronto} | @kkakey") +

  ggsave("plot.png")
```


