---
title: "2021-01-19-Kenya_Census"
author: "Kristen A, kkakey"
date: "1/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(ggtext)
```

```{r}
crops <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-19/crops.csv')

# https://africaopendata.org/dataset/kenya-counties-shapefile/resource/0b78f25e-494e-4258-96b8-a3ab2b35b121
kenya <-  read_sf("./raw-data/kenyan-counties/County.shp", crs=4326)
```

```{r}
# the top crops produced behind general crops in Kenya are avocados and mangos
crops %>%
  filter(SubCounty=='KENYA') %>%
  pivot_longer(!SubCounty) %>%
  arrange(desc(value)) %>%
  top_n(3)
```


```{r}
crops %>%
  filter(!SubCounty=='KENYA') %>%
  select(SubCounty, Farming, Avocado, Mango) %>%
  mutate(tot_prod_ava = round(Avocado / 966976,3)*100,
         tot_prod_farm = round(Farming / 6354211,3)*100,
         tot_prod_mango = round(Mango / 796867,3)*100,)-> df

# difference between avacode vs mango production
df <- df %>%
  mutate_all(funs(replace_na(.,0))) %>%
  mutate(diff = tot_prod_ava - tot_prod_mango) %>%
  filter(!c(tot_prod_ava==0 & tot_prod_mango==0))


# join data
kenya <- kenya %>%
  mutate(SubCounty = toupper(COUNTY)) %>%
  left_join(.,df, by="SubCounty")
```

```{r}
ggplot() +
  geom_sf(data=kenya, aes(fill=diff), size=.3, color="grey10") +
  scale_fill_gradient2(low = "#ffc324", mid = "grey99",
        high = "#6ba304", midpoint = 0, space = "Lab",
        na.value = "#DCBBA8",limit = c(-10,10), 
        breaks = c(-5,0,5), labels = c("-5%", "Even", "5%"),
        name = "") +
  theme_void() +
  coord_sf(clip = "off") +
  theme(text = element_text(family = "Varela Round"),
        legend.direction="horizontal",
        legend.position = c(.35,.009),
        legend.justification = c(1,-.1),
        plot.background = element_rect(fill="#D1C4E9",
                                       color="#D1C4E9"),
        panel.background = element_rect(fill="#D1C4E9",
                                        color="#D1C4E9"),
        plot.margin = unit(c(t=4,l=0,b=0,r=0), "cm"),
        plot.title = element_text(hjust=.5, vjust=10.9),
        legend.text = element_text(size=6),
        plot.caption = element_text(size=6, hjust=1.3, vjust=10)) +
  geom_richtext(aes(x=38,y=7.5,
                    label=paste0(
      "<span style = 'color:black'>","Avacodo and mango producers are two major
      farming<br> populations in Kenya. This map shows the
      population<br>dispersion of these two crop producers in relation to one
      another.
      <br><br>The southern counties have more","</span>",
      " <span style = 'color:#DDA303; font-size:10pt'>**mango**</span>",
      " <span style = 'color:black'>","farmers than ","</span>",
      "<span style = 'color:#6ba304; font-size:10pt'>**avacodo**</span> ",
      "<span style = 'color:black'>",
      "farmers<br>while the inverse holds for western counties.",
      " In the north, many counties have<br>",
      " <span style = 'color:#835134; font-size:10pt'>**no data**</span> ",
      "<span style = 'color:black'>","on these farmers,",
      " indicating these farmers are mainly located in the<br>south and south-west 
      of the country.", "</span>"),
                    family="Varela Round"), 
                    fill = NA, label.color = NA, size=3, color="#4D1F04") +
  ggtitle("Avacodo and Mango Producers in Kenya") +
  labs(caption = "Data: rKenyaCensus | @kkakey") +
  ggsave('plot.png', dpi=500)
```



