---
title: "Untitled"
author: "Kristen A, kkakey"
date: "7/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(ggtext)
library(animation)
library(gganimate)
```

```{r}
animal_rescues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-29/animal_rescues.csv')
```

```{r}
animal_rescues[animal_rescues$animal_group_parent=="cat",]$animal_group_parent <- "Cat"
```

```{r}
top_animals <- animal_rescues %>%
  group_by(animal_group_parent) %>%
  tally() %>%
  arrange(desc(n)) %>%
  head(3) %>%
  pull(animal_group_parent)
```

```{r}
animal_rescues_sf <- animal_rescues %>%
  filter(easting_m!="NULL") %>%
  mutate(easting = as.numeric(easting_m),
         morthing = as.numeric(northing_m)) %>%
  select(!c(latitude, longitude))

## transform dataframe to spatial dataframe
animal_rescues_sf <- st_as_sf(animal_rescues_sf, coords = c("easting", "morthing"), crs= "EPSG:4326")

## save to shapefile
# st_write(animal_rescues_sf, "./output-data/animal_rescues_sf.shp", append=T)
## do some clipping to inner London in QGIS (was running into some problems in R)

london <- read_sf("./output-data/london_clipped_27700.shp")
london <- st_transform(london, crs = st_crs(animal_rescues_sf))

city_outline <- read_sf("./raw-data/lp-consultation-oct-2009-inner-outer-london-shp/lp-consultation-oct-2009-inner-outer-london.shp")

animal_rescues_sf2 <- read_sf("./output-data/animal_rescues_clipped.shp")
animal_rescues_sf2 <- st_transform(animal_rescues_sf2, crs = st_crs(animal_rescues_sf))

pal <- c("#EAD94C", "#C3423F", "#44FFD1")
```

```{r}
all_years <- seq(2009,2020,1)

saveGIF({
for (yr in all_years) {

    cat_count <- animal_rescues_sf2[animal_rescues_sf2$cal_yer==yr,] %>%
      filter(anml_g_=="Cat") %>% nrow(.)
    
    dog_count <- animal_rescues_sf2[animal_rescues_sf2$cal_yer==yr,] %>%
      filter(anml_g_=="Dog") %>% nrow(.)
    
    bird_count <- animal_rescues_sf2[animal_rescues_sf2$cal_yer==yr,] %>%
      filter(anml_g_=="Bird") %>% nrow(.)
    
    plot <- ggplot() +
      geom_sf(data=london, color="#1B1B1E", fill="#373F51", size=.01) +
      geom_sf(data=animal_rescues_sf2[animal_rescues_sf2$cal_yer==yr,] %>%
                   filter(anml_g_ %in% top_animals), 
            size=.5, aes(color=as.factor(anml_g_))) +
      theme_void() +
      theme(plot.background = element_rect(fill="#487281", color=NA),
            panel.background = element_rect(fill="#487281", color=NA),
            legend.position = "none",
            text = element_text(family = "AveriaSerifLibre-Regular"),
            plot.title = element_text(size=10, hjust=.5),
            plot.subtitle = element_markdown(size=8.5, hjust=.5)) +
      scale_color_manual(values = pal) +
      ggtitle(paste("London Fire Brigade Animal Rescues", yr)) +
      labs(subtitle = paste0("<span style='color:#44FFD1'>Dogs</span>",
                            "<span style='color:black'> ",dog_count ,"</span><br>",
                            # hacky way to add spaces
                            "<span style='color:#487281; font-size:5pt'>...</span>",
                            "<span style='color:#C3423F'>Cats</span>",
                            paste("<span style='color:black'> ",cat_count ,"</span><br>"),
                            "<span style='color:#EAD94C'> Birds </span>",
                            paste("<span style='color:black'> ",bird_count ,"</span>"))) 
    
    print(plot)
  }
  }, movie.name="animal_rescue.gif", ani.width = 1200, ani.height = 1200, interval = 1.3, 
    nmax=350, ani.res=300, end_pause = 3, convert="convert")
```

```{r}
p <- animal_rescues %>%
  filter(animal_group_parent %in% top_animals, cal_year<2021) %>%
  count(animal_group_parent, cal_year) %>%
  ggplot(., aes(cal_year, n, color=as.factor(animal_group_parent))) + 
  geom_point() +
  geom_line() +
  theme(plot.background = element_rect(fill="#487281", color=NA),
            panel.background = element_rect(fill="#487281", color=NA),
            legend.position = "none",
            text = element_text(family = "AveriaSerifLibre-Regular"),
          axis.text = element_text(color="black"), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  xlab("Year") + ylab("Number of Rescues") +
  scale_x_continuous(breaks = seq(2009,2020)) +
  scale_color_manual(values = pal) + 
  transition_reveal(cal_year)

anim <- animate(p, duration = 15.6, width=5, height=5, units = "in", res = 300, fps=10)
magick::image_write(anim, path="animation2.gif")
```


Shapefiles
- City of London buildings 
    - https://twitter.com/undertheraedar/status/517955754368970752 
    - https://drive.google.com/file/d/0B0kRhiw4fD7uQzU3MzBMRzFfSFk/view?resourcekey=0-wVX6FKxK5Kx5hZ8GJnolDw
- Inner London boundary (used for clipping)
    - http://ubdc.gla.ac.uk/dataset/inner-and-outer-london-boundaries-london-plan-consultation-2009/resource/684e59f2-9208-4da1-bf67-d8dfeb72c047



