---
title: "2020-06-09-African American Achievements"
author: "Kristen A"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message = F)
```

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')
```

I used Ben Keen's tutorial, ["Creating a Timeline Graphic Using R and ggplot2,"](https://benalexkeen.com/creating-a-timeline-graphic-using-r-and-ggplot2/) to create this. It is very helpful in learning how to create timeline visualizations!


```{r}
df$new_year <- df$year
df <- df %>%
  separate(new_year, into = c("century", "new_year"), sep = 2) %>%
  select(!new_year)
df$cent <- as.numeric(df$century) + 1
df$century <- as.factor(df$cent)

status_colors <- c("#0070C0", "#00B050", "#FFC000", "#C00000")

```

*********************************************************************************************

## 18th Century Acheivements

```{r}
df_18 <- df[df$cent==18,]
```

```{r}
positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "year"=unique(df_18$year),
    "position"=rep(positions, length.out=length(unique(df_18$year))),
    "direction"=rep(directions, length.out=length(unique(df_18$year)))
)

df_18 <- merge(x=df_18, y=line_pos, by="year",all = TRUE)
df_18 <- df_18[with(df_18, order(year)), ]


text_offset <- 0.05

df_18 <- df_18 %>%
  group_by(year) %>%
  mutate(year_count = n())


df_18$text_position <- (df_18$year_count * text_offset * df_18$direction) + df_18$position
```

```{r}
year_buffer <- 2
year_range <- df_18$year

year_format <- format(year_range)
year_df_18 <- data.frame(year_range, year_format)
```

```{r}
cent_range <- seq(min(df_18$cent) , max(df_18$cent) , by=1)

cent_format <- format(cent_range)
cent_df_18 <- data.frame(cent_range, cent_format)
```

```{r}
# manually adjust line lengths and text positions
df_18[df_18$year_count == 1,]$position[3] <- 0.5
df_18[df_18$year_count == 1,]$position[8] <- 0.2
df_18[with(df_18, year_count == 1 & position < 0), ]$text_position <- df_18[with(df_18, year_count == 1 & position < 0), ]$position - .3
df_18[with(df_18, year_count == 1 & position > 0), ]$text_position <- df_18[with(df_18, year_count == 1 & position > 0), ]$position + .3
df_18[with(df_18, year_count == 1), ]$text_position[c(2,5)] <- df_18[with(df_18, year_count == 1), ]$text_position[c(2,5)] + .2
df_18[with(df_18, year_count == 1), ]$text_position[c(3:4)] <- df_18[with(df_18, year_count == 1), ]$text_position[c(3:4)] - .15
df_18[with(df_18, year_count == 1), ]$text_position[6] <- df_18[with(df_18, year_count == 1), ]$text_position[6] - .18
df_18[with(df_18, year_count == 1), ]$text_position[9] <- df_18[with(df_18, year_count == 1), ]$text_position[9] - .18
df_18[with(df_18, year_count == 1), ]$text_position[10] <- df_18[with(df_18, year_count == 1), ]$text_position[10] - .25
df_18[with(df_18, year_count == 1), ]$position[10] <- df_18[with(df_18, year_count == 1), ]$position[10] - .25
df_18[df_18$year_count == 1,]$position[8] <- 0
```

```{r}
timeline_plot<-ggplot(df_18,aes(x=year,y=0, col="#ff9900", label=accomplishment))
timeline_plot<-timeline_plot

timeline_plot<-timeline_plot+theme_classic()
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                color = "#b5b3b1", size=0.3)


# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df_18[df_18$year_count == 1,], aes(y=position,yend=0,xend=year), color='#b5b3b1', size=0.2)

timeline_plot<- timeline_plot + coord_cartesian(ylim =c(-1.75, 1.75))

# Plot scatter points at zero and date
timeline_plot<- timeline_plot+geom_point(aes(y=0))

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.text.x =element_blank(),
                 axis.ticks.x =element_blank(),
                 axis.line.x =element_blank(),
                 legend.position = "bottom"
                )

# Show text for each year 
timeline_plot<-timeline_plot+geom_text(data=year_df_18, 
                                       aes(x=year_range+.4,y=-0.15,label=year_format),size=2.5,vjust=0.5, color='white', angle=90) +
                  theme(text=element_text(family="Merriweather")) +
  ggtitle("African American Achievements") + labs(subtitle = "18th Century")



df_18$labs <- vector(mode="character", length=length(df_18$accomplishment))
df_18$labs[c(1, 10:12)] <- stringr::str_wrap(df_18$accomplishment[c(1, 10:12)], width = 12)
df_18$labs[c(2:9)] <- stringr::str_wrap(df_18$accomplishment[c(2:9)], width = 25)


timeline_plot<-timeline_plot+geom_text(data=df_18[df_18$year_count == 1,],aes(y=text_position, label=labs),size=2.6) +
                  theme(text=element_text(family="Merriweather Bold"))

timeline_plot <-  timeline_plot+theme(panel.background = element_rect(colour = "#242322", fill=NA),
                                      plot.background = element_rect(fill = '#242322'),
                                      plot.title = element_text(color="white"),
                                      plot.subtitle = element_text(color="white"),
                                      legend.position = "none") +
                    scale_color_manual(values="#ED6A5A") 

timeline_plot
ggsave(plot = last_plot(), filename = "18th-century.png", dpi = 300, width = 8, height = 5)
```


*********************************************************************************************

## 19th Century Acheivements

```{r}
df_19 <- df[df$cent==19,]
```

```{r}
positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "year"=unique(df_19$year),
    "position"=rep(positions, length.out=length(unique(df_19$year))),
    "direction"=rep(directions, length.out=length(unique(df_19$year)))
)

df_19 <- merge(x=df_19, y=line_pos, by="year",all = TRUE)
df_19 <- df_19[with(df_19, order(year)), ]


text_offset <- 0.05

df_19 <- df_19 %>%
  group_by(year) %>%
  mutate(year_count = n())


df_19$text_position <- (df_19$year_count * text_offset * df_19$direction) + df_19$position
```

```{r}
year_buffer <- 2
year_range <- df_19$year

year_format <- format(year_range)
year_df_19 <- data.frame(year_range, year_format)
```

```{r}
cent_range <- seq(min(df_19$cent) , max(df_19$cent) , by=1)

cent_format <- format(cent_range)
cent_df_19 <- data.frame(cent_range, cent_format)
```

```{r}
# create decade variable
floor_decade = function(value){ return(value - value %% 10) }
df_19$decade <- floor_decade(df_19$year)

set.seed(99)
sam <- replicate(10, sample(1:2, 1, prob=c(.7, .3)))
df_19 %>%
  group_by(decade) %>% 
  nest() %>%            
  ungroup() %>% 
  mutate(n = sam) %>% 
  mutate(samp = map2(data, n, sample_n)) %>% 
  select(-c(data,n)) %>%
  unnest(samp) -> text_df
text_df %>%
  select(accomplishment) %>%
  pull(accomplishment) -> text_19


positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "year"=unique(text_df$year),
    "position"=rep(positions, length.out=length(unique(text_df$year))),
    "direction"=rep(directions, length.out=length(unique(text_df$year)))
)

text_df <- merge(x=text_df, y=line_pos, by="year",all = TRUE)
text_df <- text_df[with(text_df, order(year)), ]


text_offset <- 0.05

text_df <- text_df %>%
  group_by(year) %>%
  mutate(year_count = n())


text_df$text_position <- (text_df$year_count * text_offset * text_df$direction.x) + text_df$position.x
```

```{r}
# select which texts to wrap
text_df$labs <- vector(mode="character", length=length(text_df$accomplishment))
text_df$labs <- stringr::str_wrap(text_df$accomplishment, width = 12)
text_df$labs[c(2:9, 12)] <- stringr::str_wrap(df_19$accomplishment[c(2:9, 12)], width = 25)
```

```{r}
# remove some year labels
remove <- c("1822", "1836", "1853", "1862", "1864", "1866", "1869", "1875", "1877", "1879", "1881", "1882","1884", "1891", "1898")
year_df_19 <- year_df_19[!year_df_19$year_range %in% remove, ]
```

```{r}
# manually adjust line lengths and text positions
text_df$text_position[text_df$text_position>0] <- text_df$text_position[text_df$text_position>0] + .2
text_df$text_position[text_df$text_position<0] <- text_df$text_position[text_df$text_position<0] - .2

df_19[df_19$position == -1.5,]$position <- -1.3
df_19[df_19$position == -1.3,]$text_position <- df_19[df_19$position == -1.3,]$text_position -.2


text_df$text_position[1] <- text_df$text_position[1] - .2
text_df$text_position[4] <- text_df$text_position[4] + .1
text_df$text_position[6] <- text_df$text_position[6] + .2
text_df$text_position[9] <- text_df$text_position[9] + .2
text_df$text_position[10] <- text_df$text_position[10] + .2
text_df$text_position[11] <- text_df$text_position[11] + .2
text_df$text_position[12] <- text_df$text_position[12] + .1
```

```{r}
timeline_plot<-ggplot(df_19,aes(x=year,y=0, col="#ff9900", label=accomplishment))
timeline_plot<-timeline_plot

timeline_plot<-timeline_plot+theme_classic()
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                color = "#b5b3b1", size=0.3)


# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df_19[df_19$accomplishment %in% text_19,], aes(y=position,yend=0,xend=year), color='#b5b3b1', size=0.2)

timeline_plot<- timeline_plot + coord_cartesian(ylim =c(-1.75, 1.75))

# Plot scatter points at zero and date
timeline_plot<- timeline_plot+geom_point(aes(y=0))

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.text.x =element_blank(),
                 axis.ticks.x =element_blank(),
                 axis.line.x =element_blank(),
                 legend.position = "bottom"
                )

# Show text for each year 
timeline_plot<-timeline_plot+geom_text(data=year_df_19, 
                                       aes(x=year_range+.4,y=-0.15,label=year_format),size=2.5,vjust=0.5, color='white', angle=90) +
                  theme(text=element_text(family="Merriweather")) 


timeline_plot<-timeline_plot+geom_text(data=text_df,aes(y=text_position, label=labs),size=2.6) +
                  theme(text=element_text(family="Merriweather Bold")) +
                  ggtitle("African American Achievements") + labs(subtitle = "19th Century")

timeline_plot <-  timeline_plot+theme(panel.background = element_rect(colour = "#242322", fill=NA),
                                      plot.background = element_rect(fill = '#242322'),
                                      plot.title = element_text(color="white"),
                                      plot.subtitle = element_text(color="white"),
                                      legend.position = "none") +
                    scale_color_manual(values="#CCD60A") 

timeline_plot
ggsave(plot = last_plot(), filename = "19th-century.png", dpi = 300, width = 8, height = 5)
```


*********************************************************************************************

## 20th Century Acheivements

```{r}
df_20 <- df[df$cent==20,]
```

```{r}
positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
  "year"=unique(df_20$year),
  "position"=rep(positions, length.out=length(unique(df_20$year))),
  "direction"=rep(directions, length.out=length(unique(df_20$year)))
)

df_20 <- merge(x=df_20, y=line_pos, by="year",all = TRUE)
df_20 <- df_20[with(df_20, order(year)), ]


text_offset <- 0.05

df_20 <- df_20 %>%
  group_by(year) %>%
  mutate(year_count = n())


df_20$text_position <- (df_20$year_count * text_offset * df_20$direction) + df_20$position
```

```{r}
year_buffer <- 2
year_range <- df_20$year

year_format <- format(year_range)
year_df_20 <- data.frame(year_range, year_format)
```

```{r}
cent_range <- seq(min(df_20$cent) , max(df_20$cent) , by=1)

cent_format <- format(cent_range)
cent_df_20 <- data.frame(cent_range, cent_format)
```

```{r}
# create decade variable
floor_decade = function(value){ return(value - value %% 10) }
df_20$decade <- floor_decade(df_20$year)

set.seed(9)
sam <- replicate(10, sample(1:2, 1, prob=c(.7, .3)))
# add text to 30s
sam[4] <- 2
df_20 %>%
  group_by(decade) %>% 
  nest() %>%            
  ungroup() %>% 
  mutate(n = sam) %>% 
  mutate(samp = map2(data, n, sample_n)) %>% 
  select(-c(data,n)) %>%
  unnest(samp) -> text_df
text_df %>%
  select(accomplishment) %>%
  pull(accomplishment) -> text_20


positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
  "year"=unique(text_df$year),
  "position"=rep(positions, length.out=length(unique(text_df$year))),
  "direction"=rep(directions, length.out=length(unique(text_df$year)))
)

text_df <- merge(x=text_df, y=line_pos, by="year",all = TRUE)
text_df <- text_df[with(text_df, order(year)), ]


text_offset <- 0.05

text_df <- text_df %>%
  group_by(year) %>%
  mutate(year_count = n())


text_df$text_position <- (text_df$year_count * text_offset * text_df$direction.x) + text_df$position.x
```

```{r}
# select which texts to wrap
text_df$labs <- vector(mode="character", length=length(text_df$accomplishment))
text_df$labs <- stringr::str_wrap(text_df$accomplishment, width = 12)
text_df$labs[12] <- stringr::str_wrap(text_df$accomplishment[12], width = 11)
text_df$labs[c(2:10)] <- stringr::str_wrap(df_20$accomplishment[c(2:10)], width = 25)
```

```{r}
# keep even years
year_df_20 <- year_df_20[year_df_20$year_range%%2==0,]
```

```{r}
# manually adjust line lengths and text positions
text_df$text_position[text_df$text_position>0] <- text_df$text_position[text_df$text_position>0] + .2
text_df$text_position[text_df$text_position<0] <- text_df$text_position[text_df$text_position<0] - .2

text_df$text_position[5] <- text_df$text_position[5] + .05
text_df$text_position[6] <- text_df$text_position[6] - .08


text_df$text_position[6] <- text_df$text_position[6] + 1.43
df_20[df_20$accomplishment %in% text_20,]$position[6] <- df_20[df_20$accomplishment %in% text_20,]$position[6] + .8

text_df$text_position[5] <- text_df$text_position[5] + .3
df_20[df_20$accomplishment %in% text_20,]$position[5] <- df_20[df_20$accomplishment %in% text_20,]$position[5] + .3

text_df$text_position[4] <- text_df$text_position[4] + .2
df_20[df_20$accomplishment %in% text_20,]$position[4] <- df_20[df_20$accomplishment %in% text_20,]$position[4] + .2
df_20[df_20$accomplishment %in% text_20,]$position[12] <- df_20[df_20$accomplishment %in% text_20,]$position[12] + .2

df_20[df_20$accomplishment %in% text_20,]$position[1] <- df_20[df_20$accomplishment %in% text_20,]$position[1] - .25

text_df$text_position[11] <- text_df$text_position[11] - .2
df_20[df_20$accomplishment %in% text_20,]$position[11] <- df_20[df_20$accomplishment %in% text_20,]$position[11] - .25
```

```{r}
timeline_plot<-ggplot(df_20,aes(x=year,y=0, col="#ff9900", label=accomplishment))
timeline_plot<-timeline_plot

timeline_plot<-timeline_plot+theme_classic()
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                                        color = "#b5b3b1", size=0.3)


# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df_20[df_20$accomplishment %in% text_20,], aes(y=position,yend=0,xend=year), color='#b5b3b1', size=0.2)

timeline_plot<- timeline_plot + coord_cartesian(ylim =c(-1.75, 1.75))

# Plot scatter points at zero and date
timeline_plot<- timeline_plot+geom_point(aes(y=0))

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                                   axis.text.y=element_blank(),
                                   axis.title.x=element_blank(),
                                   axis.title.y=element_blank(),
                                   axis.ticks.y=element_blank(),
                                   axis.text.x =element_blank(),
                                   axis.ticks.x =element_blank(),
                                   axis.line.x =element_blank(),
                                   legend.position = "bottom"
)

# Show text for each year 
timeline_plot<-timeline_plot+geom_text(data=year_df_20, 
                                       aes(x=year_range+.4,y=-0.15,label=year_format),size=2.5,vjust=0.5, color='white', angle=90) +
  theme(text=element_text(family="Merriweather")) 


timeline_plot<-timeline_plot+geom_text(data=text_df,aes(y=text_position, label=labs),size=2.6) +
  theme(text=element_text(family="Merriweather Bold")) +
  ggtitle("African American Achievements") + labs(subtitle = "20th Century")

timeline_plot <-  timeline_plot+theme(panel.background = element_rect(colour = "#242322", fill=NA),
                                      plot.background = element_rect(fill = '#242322'),
                                      plot.title = element_text(color="white"),
                                      plot.subtitle = element_text(color="white"),
                                      legend.position = "none") +
  scale_color_manual(values="#3993DD") 

#remove years right next to each other
timeline_plot
ggsave(plot = last_plot(), filename = "20th-century.png", dpi = 300, width = 8, height = 5)
```

*********************************************************************************************

## 21st Century Acheivements

```{r}
df_21 <- df[df$cent==21,]
```

```{r}
positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
  "year"=unique(df_21$year),
  "position"=rep(positions, length.out=length(unique(df_21$year))),
  "direction"=rep(directions, length.out=length(unique(df_21$year)))
)

df_21 <- merge(x=df_21, y=line_pos, by="year",all = TRUE)
df_21 <- df_21[with(df_21, order(year)), ]


text_offset <- 0.05

df_21 <- df_21 %>%
  group_by(year) %>%
  mutate(year_count = n())


df_21$text_position <- (df_21$year_count * text_offset * df_21$direction) + df_21$position
```


```{r}
year_buffer <- 2
year_range <- df_21$year

year_format <- format(year_range)
year_df_21 <- data.frame(year_range, year_format)
```

```{r}
cent_range <- seq(min(df_21$cent) , max(df_21$cent) , by=1)

cent_format <- format(cent_range)
cent_df_21 <- data.frame(cent_range, cent_format)
```


```{r}
df_21 %>%
  group_by(year) %>% 
  sample_n(1) -> text_df
text_df <- text_df[c(2:11,13:19),]

text_df %>%
  arrange(year) %>%
  select(accomplishment) %>%
  pull(accomplishment) -> text_21


positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
  "year"=unique(text_df$year),
  "position"=rep(positions, length.out=length(unique(text_df$year))),
  "direction"=rep(directions, length.out=length(unique(text_df$year)))
)

text_df <- merge(x=text_df, y=line_pos, by="year",all = TRUE)
text_df <- text_df[with(text_df, order(year)), ]


text_offset <- 0.05

text_df <- text_df %>%
  group_by(year) %>%
  mutate(year_count = n())


text_df$text_position <- (text_df$year_count * text_offset * text_df$direction.x) + text_df$position.x
```

```{r}
# select which texts to wrap
text_df$labs <- vector(mode="character", length=length(text_df$accomplishment))
text_df$labs <- stringr::str_wrap(text_df$accomplishment, width = 12)
text_df$labs[c(2:10,16)] <- stringr::str_wrap(df_21$accomplishment[c(2:10,16)], width = 25)
```

```{r}
# manually adjust line lengths and text positions
text_df$text_position[text_df$text_position>0] <- text_df$text_position[text_df$text_position>0] + .2
text_df$text_position[text_df$text_position<0] <- text_df$text_position[text_df$text_position<0] - .2

text_df$text_position[2] <- text_df$text_position[2] - .2
df_21[df_21$accomplishment %in% text_21,]$position[2] <- df_21[df_21$accomplishment %in% text_21,]$position[2] - .2

df_21[df_21$accomplishment %in% text_21,]$position[3] <- df_21[df_21$accomplishment %in% text_21,]$position[3] - .2
df_21[df_21$accomplishment %in% text_21,]$position[9] <- df_21[df_21$accomplishment %in% text_21,]$position[9] - .2

text_df$text_position[12] <- text_df$text_position[12] - .4

text_df$text_position[14] <- text_df$text_position[14] + .38
df_21[df_21$accomplishment %in% text_21,]$position[14] <- df_21[df_21$accomplishment %in% text_21,]$position[14] + .55


text_df$text_position[15] <- text_df$text_position[15] - .42
df_21[df_21$accomplishment %in% text_21,]$position[15] <- df_21[df_21$accomplishment %in% text_21,]$position[15] - .45

text_df$text_position[16] <- text_df$text_position[16] + .17
df_21[df_21$accomplishment %in% text_21,]$position[16] <- df_21[df_21$accomplishment %in% text_21,]$position[16] + .15

df_21[df_21$accomplishment %in% text_21,]$position[17] <- df_21[df_21$accomplishment %in% text_21,]$position[17] - .25

df_21[df_21$accomplishment %in% text_21,]$position[15] <- df_21[df_21$accomplishment %in% text_21,]$position[15] - .2
df_21[df_21$accomplishment %in% text_21,]$position[11] <- df_21[df_21$accomplishment %in% text_21,]$position[11] - .3
df_21[df_21$accomplishment %in% text_21,]$position[10] <- df_21[df_21$accomplishment %in% text_21,]$position[10] + .11
text_df$text_position[1] <- text_df$text_position[1] - .2
text_df$text_position[2] <- text_df$text_position[2] - .1

text_df$text_position[4] <- text_df$text_position[4] - .2
df_21[df_21$accomplishment %in% text_21,]$position[4] <- df_21[df_21$accomplishment %in% text_21,]$position[4] - .2

text_df <- text_df[-5,]
df_21[df_21$accomplishment %in% text_21,]$position[5] <- 0
```

```{r}
timeline_plot<-ggplot(df_21,aes(x=year,y=0, col="#ff9900", label=accomplishment))
timeline_plot<-timeline_plot

timeline_plot<-timeline_plot+theme_classic()
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                                        color = "#b5b3b1", size=0.3)


# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df_21[df_21$accomplishment %in% text_21,], aes(y=position,yend=0,xend=year), color='#b5b3b1', size=0.2)

timeline_plot<- timeline_plot + coord_cartesian(ylim =c(-1.75, 1.75))

# Plot scatter points at zero and date
timeline_plot<- timeline_plot+geom_point(aes(y=0))

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                                   axis.text.y=element_blank(),
                                   axis.title.x=element_blank(),
                                   axis.title.y=element_blank(),
                                   axis.ticks.y=element_blank(),
                                   axis.text.x =element_blank(),
                                   axis.ticks.x =element_blank(),
                                   axis.line.x =element_blank(),
                                   legend.position = "bottom"
)

# Show text for each year 
timeline_plot<-timeline_plot+geom_text(data=year_df_21, 
                                       aes(x=year_range,y=-0.15,label=year_format),size=2.5,vjust=0.5, color='white', angle=90) +
  theme(text=element_text(family="Merriweather")) 


timeline_plot<-timeline_plot+geom_text(data=text_df,aes(y=text_position, label=labs),size=2.6) +
  theme(text=element_text(family="Merriweather Bold")) +
  ggtitle("African American Achievements") + labs(subtitle = "21st Century")

timeline_plot <-  timeline_plot+theme(panel.background = element_rect(colour = "#242322", fill=NA),
                                      plot.background = element_rect(fill = '#242322'),
                                      plot.title = element_text(color="white"),
                                      plot.subtitle = element_text(color="white"),
                                      legend.position = "none") +
  scale_color_manual(values="#FFD972") 

timeline_plot
ggsave(plot = last_plot(), filename = "21st-century.png", dpi = 300, width = 8, height = 5)
```



