---
title: "Untitled"
author: "Kristen A, kkakey"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magick) 
library(scales) 
library(imager)
```


```{r}
artwork <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-12/artwork.csv')
artwork <- artwork %>%
  filter(!is.na(year),!is.na(thumbnailUrl)) %>%
  mutate(decade = year - year %% 10)


## count paintings by decade
## keep only decades with 8+ decades from the decade
artwork %>%
  count(decade) %>%
  filter(n>=20) %>%
  select(decade) %>% pull() -> years

n_sam <- 20
### randomly sample 8 art pieces each decade
set.seed(99)
art_sample <- artwork %>%
  arrange(year) %>%
  filter(decade %in% years) %>%
  group_by(decade) %>% 
  sample_n(n_sam)
```

```{r}
#### function from: https://chichacha.netlify.app/2019/01/19/extracting-colours-from-your-images-with-image-quantization/
get_colorPal <- function(im, n=3, cs="RGB"){
  #print(cs) 
  tmp <-im %>% image_resize("100") %>% 
     ## reducing colours! different colorspace gives you different result
    image_quantize(max=n, colorspace=cs) %>%  
    ## I'm converting, becauase I want to use as.data.frame function in imager package.
    magick2cimg() %>%  
    ## i like sorting colour by hue rather than RGB (red green blue)
    RGBtoHSV() %>% 
    #3 making it wide makes it easier to output hex colour
    as.data.frame(wide="c") %>%  
    mutate(hex=hsv(rescale(c.1, from=c(0,360)),c.2,c.3),
           hue = c.1,
           sat = c.2,
           value = c.3) %>%
    count(hex, hue, sat,value, sort=T) %>% 
    mutate(colorspace = cs)
  ## I want data frame as a result.
  return(tmp %>% select(colorspace,hex,hue,sat,value,n)) 
  
}

```


```{r}
art_sample <- art_sample %>%
  select(title, artist, year, acquisitionYear, medium, decade,
         accession_number, thumbnailUrl, url)

art_sample[,'color1'] <- "-"
art_sample[,'color2'] <- "-"
art_sample[,'color3'] <- "-"


start_time <- Sys.time()
for (i in 1:nrow(as.tibble(art_sample$thumbnailUrl))) {
  try({ im <- image_read(art_sample$thumbnailUrl[i])}, silent=F)
  my_colors <- get_colorPal(im) %>% pull(hex)
  art_sample[i,'color1'] <- my_colors[1]
  art_sample[i,'color2'] <- my_colors[2]
  art_sample[i,'color3'] <- my_colors[3]
}
end_time <- Sys.time()
end_time - start_time

### For those with a color palette < 3, try again: ###
### 4
for (i in 1:nrow(as.tibble(art_sample[is.na(art_sample['color3']) & !is.na(art_sample['color2']),]$thumbnailUrl))) {
  print(i)
  try({ im <- image_read(art_sample$thumbnailUrl[i])}, silent=F)
  my_colors <- get_colorPal(im, 4) %>% pull(hex)
  art_sample[is.na(art_sample['color3']) & !is.na(art_sample['color2']),][i,'color1'] <- my_colors[1]
  art_sample[is.na(art_sample['color3']) & !is.na(art_sample['color2']),][i,'color2'] <- my_colors[2]
  art_sample[is.na(art_sample['color3']) & !is.na(art_sample['color2']),][i,'color3'] <- my_colors[3]
}


### 5
for (i in 1:nrow(as.tibble(art_sample[is.na(art_sample['color2']),]$thumbnailUrl))) {
  print(i)
  try({ im <- image_read(art_sample$thumbnailUrl[i])}, silent=F)
  my_colors <- get_colorPal(im, 5) %>% pull(hex)
  art_sample[is.na(art_sample['color2']),][i,'color1'] <- my_colors[1]
  art_sample[is.na(art_sample['color2']),][i,'color2'] <- my_colors[2]
  art_sample[is.na(art_sample['color2']),][i,'color3'] <- my_colors[3]
}

# write.csv(art_sample,"./output-data/art_sample.csv", row.names = FALSE)
```



```{r}
art_sample <- read_csv("./output-data/art_sample.csv")

# rejoin columns for additional information
artwork <- artwork %>%
  select(title, decade, accession_number, artist, acquisitionYear, medium)

art_sample <- art_sample %>%
  left_join(.,artwork, by=c("title", "decade", "accession_number"))

# create one unified list of all the colors
library(foreach)
color_list <- c()
foreach(one = art_sample$color1, two = art_sample$color2, three= art_sample$color3) %do% {
  color_list <- c(color_list, one, two, three)
}
```

```{r}
# put it all together 
X <- data.frame("y" = rep(art_sample$decade, each=3),
                "x" = rep(1:(n_sam*3), 29), 
                "color_pal" = color_list,
                "title" = rep(art_sample$title, each=3),
                "year" = rep(art_sample$year, each=3),
                "artist" = rep(art_sample$artist, each=3),
                "acuisition year" = rep(art_sample$acquisitionYear, each=3),
                "medium" = rep(art_sample$medium, each=3),
                "image_nail" = rep(art_sample$thumbnailUrl, each=3),
                "accession_number" = rep(art_sample$accession_number, each=3),
                stringsAsFactors = FALSE)

## output for shiny app
# write.csv(X,"./tate_art_app/final_df.csv", row.names = FALSE)
```

```{r}
# static plot
ggplot(data=X, aes(y,x, fill=color_pal)) +
  geom_tile(col = NA, height=1, width=9) +
  scale_fill_manual(values=color_list) +
  guides(fill = "none") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.background = element_rect(fill="white", color="white"),
        text = element_text(family="Lato"),
        plot.margin =  margin(1.5,1.5,1,1, unit="cm"),
        plot.title = element_text(vjust=2.4, size=14, hjust=.5),
        plot.subtitle = element_text(size=9, vjust=1, hjust=.5),
        plot.caption = element_text(size=7, vjust=-20, hjust=1.1),
        axis.text.y=element_blank()
        ) +
  xlab("") + ylab("") + 
  ggtitle("Color Palettes at the Tate Art Muesum") +
  labs(subtitle = "Each column includes three colors from twenty randomly selected art pieces from that decade",
       caption = "Data: Tate Art Museum | @kkakey") +
  ggsave("plot.png", width = 7, height=5)
```


```{r}
### plotly - interactive
plot <- ggplot(data=df, aes(y,x, fill=color_pal)) +
            geom_tile(col = NA, height=1, width=9,
                      aes(title=title,year=year,artist=artist,
                          acuisition.year=acuisition.year,
                          medium=medium)
            ) +
            scale_fill_manual(values=color_list) +
            guides(fill = "none") +
            theme_minimal() +
            theme(panel.grid = element_blank(),
                  plot.background = element_rect(fill="white", color="white"),
                  text = element_text(family="Lato"),
                  legend.position = "none",
                  axis.text.y=element_blank(),
                  plot.margin =  margin(1.5,1.5,1,1, unit="cm")
            ) +
            xlab("") + ylab("") 

output <- ggplotly(plot, tooltip=c("title","year","artist","acuisition.year","medium")) %>%
   layout(title = list(text = paste0('Color Palettes at the Tate Art Muesum',
                                    '<br>',
                                    '<sup>',
                                    'Each column includes three colors from twenty randomly selected art pieces from that decade',
                                    '</sup>')))
htmlwidgets::saveWidget(output, "index.html")
```














```{r}
# test run
X <- data.frame("x" = rep(c(1:n_sam), length(years)), 
                "y" = rep(years, each=n_sam), 
                "color_ex" = rep(my_colors, length(years)),
                stringsAsFactors = FALSE)

X <- data.frame("x" = 1:3, 
                "y" = 100, 200, 300, 
                "color_ex" = art_df$palette[1],
                stringsAsFactors = FALSE)


ggplot(data=X, aes(y,x, fill=color_ex)) +
  geom_tile() +
  scale_fill_manual(values=art_df$palette[1])
```



```{r}
my_colors <- get_colorPal(im) %>% pull(hex)

prismatic::color(my_colors)

ggplot(data=my_colors2, aes(x=1, y=value, fill=hex)) +
  geom_tile(interpolate=T, width=.01) +
  scale_fill_manual(values = my_colors2$hex)

artwork$url[1]
im <- image_read(artwork$thumbnailUrl[1])
artwork




my_colors2 

df <- expand.grid(x = 0:5, y = 0:5)
df$z <- runif(nrow(df))
ggplot(df, aes(1880, 1, fill = "#4F4539")) + geom_raster(hjust = 0, vjust = 0)
```


```{r}
params <- list(im=list(im), 
               n=12) ## gray fails so I've removed it...

my_colors2 <- pmap_df(params,get_colorPal)

my_colors2 %>%  
  group_by(colorspace) %>%
  mutate(ypos=row_number(value)) %>%  ## I decided to stack colours by value. 
  ggplot(aes(x=fct_infreq(colorspace),y=ypos, fill=hex)) +  
  geom_tile() +
  geom_text(aes(label=hex), color="#ffffffbe", 
            size=4) +
  scale_fill_identity() +
  scale_y_continuous(breaks=NULL) +
  # theme_void(base_family="Roboto Condensed") +
  coord_flip(ylim=c(1,8)) +
  theme(axis.text = element_text(color = "black", hjust=1)) +
  labs(caption="Using different colourspce to reduce the colour used in images")
```



### color palette of tate art